# config.yaml - CONSERVATIVE URL filtering (replace your current config)
url_filters:
  # Only exclude obvious tracking parameters
  excluded_parameters:
    - "utm_source"
    - "utm_medium" 
    - "utm_campaign"
    - "fbclid"
    - "gclid"
    - "sessionid"
    
  # Only exclude clear admin/system pages
  excluded_pages:
    - "/wp-admin/"
    - "/admin/"
    - "/login"
    - "/logout"
    - "/404.html"
    
  # Minimal regex patterns (VERY SPECIFIC)
  excluded_patterns:
    - "^.*/wp-admin/.*$"    # WordPress admin only
    - "^.*/feed/?$"         # RSS feeds only
    - "^.*\\?p=\\d+$"       # WP pagination only

analysis:
  similarity_thresholds:
    high: 0.90
    medium: 0.89
  priority_percentiles:
    high: 70  
    medium: 30
  min_clicks: 1
  min_impressions: 10
  min_queries: 1
